# Generated by Django 2.2.20 on 2021-05-21 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('datetime', models.DateTimeField(verbose_name='修改时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='单页所有人')),
            ],
            options={
                'verbose_name': '便签',
                'verbose_name_plural': '便签',
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='收藏时间')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Note', verbose_name='便签')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏所有人')),
            ],
            options={
                'verbose_name': '便签',
                'verbose_name_plural': '便签',
            },
        ),
    ]
