# Generated by Django 2.2.20 on 2021-05-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'verbose_name': '收藏便签', 'verbose_name_plural': '收藏便签'},
        ),
    ]
