# Generated by Django 2.2.20 on 2021-05-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_notetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notetag',
            name='note',
        ),
        migrations.CreateModel(
            name='NoteAndNoteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Note', verbose_name='便签')),
                ('note_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.NoteTag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签联系',
                'verbose_name_plural': '标签联系',
            },
        ),
    ]
